### ISSUE TITLE
Mapping which management APIs there are

### ISSUE THREAD

**Issue by ManondW99** [AmpersandTarski/prototype-frontend#133]
The tools menu is one of the user interface items that needs to migrate from AngularJS to Angular. This item is there in every page of a generated prototype.

![Image](https://user-images.githubusercontent.com/25156290/213462770-a01f82b4-50d5-4da6-9b6d-36bd504f166f.png)

The goal is to refactor this tools menu, so users can navigate to the management APIs
The items in that menu should:

- [x] Should refresh the page
- [x] Should redirect to the installer page 
- [x] Evaluate all rules
- [x] Run the execution engine
- [x] Navigate to the importer page; #143 
- [x] export the current data as a json file

**Comment by hanjoosten** [comment]
@ManondW99 Please elaborate: What is the purpose of this story?

**Comment by Michiel-s** [comment]
@LiWeiYeh, I noticed your commits, implementing the API calls as stated above from the menu item screenshot.

A couple of comments/request:
- Refresh page can be removed. That was a function we needed sometimes due to shortcomings in the old frontend implementation. Not needed anymore
- Other functions I would like to see as cards on a new page in the AdminModule. See the InstallerComponent in that module as an example. The InstallerComponent contains 3 cards, for the different options. A new 'UtilsComponent' (let's call it that for now), can contain several cards for the functions:
  - Evaluate all rules
  - Run the exec engine
- Population related functions I would like to see as well on cards in a separate component in the AdminModule. Let's call that one PopulationComponent. It should have cards to:
  - Export population
  - Navigate to the route/component to import population #143
- That new pages can be listed as item in the left-menu under Admin section (like with the InstallerComponent).

Other admin APIs that do not have a button/UI in the old frontend but some do need to get a card in the new frontend. They are listed in this backend API file: https://github.com/AmpersandTarski/prototype/blob/main/bootstrap/api/admin.php.
Not all of them are relevant for now, but the one that need to be included are:
* `GET /admin/installer/checksum/update` --> card on InstallerComponent
* All 5 apis under `/admin/report` --> cards on new ReportComponent
* `GET /admin/exporter/export/metamodel` --> card on PopulationComponent
* `GET /admin/utils/regenerate-all-atom-ids[/{concept}]` --> 2 cards on PopulationComponent. One without input field (regenerates all atoms) and one card with a select box to select a single concept.

**Comment by Michiel-s** [comment]
Yes. Menu item in header bar can be removed.
