### ISSUE TITLE
Create notifications for actions

### ISSUE THREAD

**Issue by LiWeiYeh** [AmpersandTarski/prototype-frontend#166]
Notifications should be shown when certain actions are done:

- [x] Updating values (such as atomic-alphanumerics) should show a notification so that the user knows this value is updated/cannot be updated/cannot be empty/etc.
- [x] Deleting values (such as an instance of an interface) should show a notification so that the user knows this value is deleted/cannot be deleted

![Image](https://user-images.githubusercontent.com/25156290/216994076-8c6ee237-d590-4d87-897d-cade0a931140.gif)

When a user does such an actions, within the network you can see the response it gives, which contains the corresponding notification message:

![Image](https://user-images.githubusercontent.com/25156290/216995596-feefa9f8-5a9e-413a-8887-c604f6d34033.gif)

- [x] Imported population .json files should show an error notification when importing the file fails #143

**Comment by byTinus** [comment]
### Main Toast module
A `MessageService` has been added to the main app component. This way, the service covers all other components, having only one `<p-toast>` object to be present at all times, instead of adding one to each component that needs it.

To use this service in a component, simply add `private messageService: MessageService` to the component constructor. Then, to send a message, add `this.messageService.add( {YOUR_MESSAGE} );` to the code. 

Here is an example (from admin/population/import/import.component.ts):
![image](https://user-images.githubusercontent.com/58219126/223455745-38c1c1b7-1d74-4f97-ac14-a131067dcf2e.png)


A message has the following fields (I added comments to clarify the more important fields):
```Typescript
export interface Message {
    severity?: string; // "success", "info", "warn" or "error"
    summary?: string; // The header of the message
    detail?: string; // The main text area of the message
    id?: any; 
    key?: string;  
    life?: number; // Time in milliseconds that the toast is displayed
    sticky?: boolean; // if true, the message stays visible until manually removed.
    closable?: boolean; // if true, adds a close button
    data?: any;
    icon?: string;
    contentStyleClass?: string;
    styleClass?: string;
}
```
(click [here](https://www.primefaces.org/primeng-v13/toast) for more specific information).

### Atomic Components
The abstract `BaseAtomicComponent` has message functionality now. This way each atomic component can easily send a message. Just call the `super.addMessage( {YOUR_MESSAGE} );` method.
